/* User Settings */
export const POST_USER_SETTINGS = 'POST_USER_SETTINGS'
export const POST_USER_SETTINGS_SUCCESS = 'POST_USER_SETTINGS_SUCCESS'
export const POST_USER_SETTINGS_ERROR = 'POST_USER_SETTINGS_ERROR'

/* Add Order */
export const POST_ADD_ORDER = 'POST_ADD_ORDER'
export const POST_ADD_ORDER_SUCCESS = 'POST_ADD_ORDER_SUCCESS'
export const POST_ADD_ORDER_ERROR = 'POST_ADD_ORDER_ERROR'
export const POST_ADD_TO_ORDER_CHECK = 'POST_ADD_TO_ORDER_CHECK'


/* Add Payment Method */
export const POST_ADD_METHOD = 'POST_ADD_METHOD'
export const POST_ADD_METHOD_SUCCES = 'POST_ADD_METHOD_SUCCESS'
export const POST_ADD_METHOD_ERROR = 'POST_ADD_METHOD_ERROR'
export const POST_ADD_METHOD_ERROR = 'POST_ADD_METHOD_ERROR'

/* Add products to kart */
export const POST_ADD_TO_KART = 'POST_ADD_TO_KART'
export const POST_ADD_TO_KART_SUCCES = 'POST_ADD_TO_KART_SUCCES'
export const POST_ADD_TO_KART_ERROR = 'POST_ADD_TO_KART_ERROR'

